language: python
addons:
    postgresql: "9.4"
python:
    - "3.4"
    - "3.5"
install: pip install -r requirements.txt
before_script:
    - psql -c "CREATE USER pupa with PASSWORD 'pupa' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE opencivicdata;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d opencivicdata
script: ./manage.py test
notifications:
    email:
        - james.p.turk@gmail.com
