# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-21 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
