# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-22 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20151021_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='rep_from_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='sen_from_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
