# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-28 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_auto_20160215_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'verbose_name_plural': 'preferences'},
        ),
    ]
