# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-29 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencivicdata', '0004_auto_20150925_0338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preferences', '0006_auto_20160228_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='opencivicdata.Bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
