# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150905155558 on 2015-09-13 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Glossary',
            new_name='Term',
        ),
    ]
